CREATE TABLE IF NOT EXISTS quizzes (
    quizID INT AUTO_INCREMENT PRIMARY KEY,
    userID VARCHAR(255) NOT NULL,
    quiz_name VARCHAR(255) NOT NULL,
    score INT NOT NULL,
    date_taken TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES user_info(userID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lessons (
    lessonID INT AUTO_INCREMENT PRIMARY KEY,
    userID VARCHAR(255) NOT NULL,
    lesson_name VARCHAR(255) NOT NULL,
    date_completed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES user_info(userID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS assessments (
    assessmentID INT AUTO_INCREMENT PRIMARY KEY,
    userID VARCHAR(255) NOT NULL,
    assessment_name VARCHAR(255) NOT NULL,
    score INT NOT NULL,
    date_taken TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES user_info(userID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS certificates (
    certificateID INT AUTO_INCREMENT PRIMARY KEY,
    userID VARCHAR(255) NOT NULL,
    certificate_name VARCHAR(255) NOT NULL,
    date_issued TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES user_info(userID) ON DELETE CASCADE
);
