INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-01", "Biologist", "Lifeeeee");
INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-02", "Computer Scientist", "Master Unemployment");
INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-03", "Chemist", "Walter White");
INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-04", "Chemical Engineer", "Taga-gawa bomba sa Middle East");
INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-05", "Civil Engineer", "Kalaban ng Architect");
INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-06", "Data Scientist", "Unemployed Number 1");
INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-07", "Doctor", "Doctor KwakKwak");
INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-08", "Math Teacher", "Teacher sa Math");
INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-09", "Nurse", "Take Cares the Patients");
INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-10", "Physicist", "Take Cares the Patients");
INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-11", "Science Teacher", "Teacher sa Science");
INSERT INTO courses (courseID, course_name, course_description) VALUES ("C-12", "Software Developer", "Unemployed Number 2");
